/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package net

import (
	"net"
	"strconv"

	corev1 "k8s.io/api/core/v1"
	discoveryv1 "k8s.io/api/discovery/v1"
	"k8s.io/apimachinery/pkg/util/sets"

	"knative.dev/networking/pkg/apis/networking"
)

// healthyAddresses takes an endpointslice object and a port name and return the set
// of addresses that implement this port.
func healthyAddresses(endpointSlice *discoveryv1.EndpointSlice, portName string) sets.Set[string] {
	var addresses int
	for _, port := range endpointSlice.Ports {
		if port.Name != nil && *port.Name == portName {
			for _, endpoint := range endpointSlice.Endpoints {
				if endpoint.Conditions.Ready == nil || *endpoint.Conditions.Ready {
					addresses += len(endpoint.Addresses)
				}
			}
			break
		}
	}

	ready := make(sets.Set[string], addresses)

	for _, port := range endpointSlice.Ports {
		if port.Name != nil && *port.Name == portName {
			for _, endpoint := range endpointSlice.Endpoints {
				if endpoint.Conditions.Ready == nil || *endpoint.Conditions.Ready {
					for _, addr := range endpoint.Addresses {
						ready.Insert(addr)
					}
				}
			}
			break
		}
	}

	return ready
}

// endpointsToDests takes an endpointslice object and a port name and returns two sets of
// ready and non-ready l4 dests in the endpointslice object which have that port.
func endpointsToDests(endpointSlice *discoveryv1.EndpointSlice, portName string) (ready, notReady sets.Set[string]) {
	var readyAddresses, nonReadyAddresses int
	for _, port := range endpointSlice.Ports {
		if port.Name != nil && *port.Name == portName {
			for _, endpoint := range endpointSlice.Endpoints {
				if endpoint.Conditions.Ready != nil && *endpoint.Conditions.Ready {
					readyAddresses += len(endpoint.Addresses)
				} else {
					nonReadyAddresses += len(endpoint.Addresses)
				}
			}
			break
		}
	}

	ready = make(sets.Set[string], readyAddresses)
	notReady = make(sets.Set[string], nonReadyAddresses)

	for _, port := range endpointSlice.Ports {
		if port.Name != nil && *port.Name == portName {
			var portStr string
			if port.Port != nil {
				portStr = strconv.Itoa(int(*port.Port))
			} else {
				// If port is not specified, we can't form a proper destination.
				// This should not happen for services generated by Kubernetes.
				continue
			}
			for _, endpoint := range endpointSlice.Endpoints {
				for _, addr := range endpoint.Addresses {
					// Prefer IP as we can avoid a DNS lookup this way.
					if endpoint.Conditions.Ready != nil && *endpoint.Conditions.Ready {
						ready.Insert(net.JoinHostPort(addr, portStr))
					} else {
						notReady.Insert(net.JoinHostPort(addr, portStr))
					}
				}
			}
			break
		}
	}

	return ready, notReady
}

// getServicePort takes a service and a protocol and returns the port number of
// the port named for that protocol. If the port is not found then ok is false.
func getServicePort(protocol networking.ProtocolType, svc *corev1.Service) (int, bool) {
	wantName := networking.ServicePortName(protocol)
	for _, p := range svc.Spec.Ports {
		if p.Name == wantName {
			return int(p.Port), true
		}
	}

	return 0, false
}
